config/routes.rb
Rails.application.routes.draw do

  resources :candidates do
    resources :comments
    resources :progressions
  end

  resources :staffs

  get  '/aa/paget',  to: 'candidates#paget'
  post '/aa/create', to: 'candidates#create_aa'

  root 'candidates#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
        has_many :comments, dependent: :destroy
        has_many :progressions, dependent: :destroy

        validates :name,  presence: true, length: { maximum: 50 }
        validates :email, presence: true, length: { maximum: 255 }
        validates :gender, presence: true
        validates :phone, presence: true
        validates :address, presence: true, length: { maximum: 255 }

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :candidate
end

app/models/progression.rb
class Progression < ApplicationRecord
  belongs_to :candidate
end

app/models/staff.rb
class Staff < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }
  validates :gender, presence: true
  validates :phone, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  # protect_from_forgery with: :null_session
  # protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }

end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

  def paget
  end

  def index
    @candidates = Candidate.all
  end

  def new
    @candidate = Candidate.new
  end

  def show
    @candidate = Candidate.find(params[:id])
  end

  def create
    @candidate = Candidate.new(candidate_params)

    if @candidate.save
      redirect_to candidates_url
    else
      render 'new'
    end
  end

  def update
    @candidate = Candidate.find(params[:id])

    if @candidate.update(candidate_params)
      redirect_to candidates_url
    else
      render 'show'
    end
  end

  def destroy
    @candidate = Candidate.find(params[:id])
    @candidate.destroy
    redirect_to candidates_url
  end

  private
  def candidate_params
    params.require(:candidate).permit(:name, :gender, :email, :phone,
                                      :address ,:source ,:source_detail ,:blacklist)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @candidate = Candidate.find(params[:candidate_id])
    @comment = @candidate.comments.create(comment_params)
    redirect_to candidate_path(@candidate)
  end

  def destroy
    @candidate = Candidate.find(params[:candidate_id])
    @comment = @candidate.comments.find(params[:id])
    @comment.destroy
    redirect_to candidate_path(@candidate)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/progressions_controller.rb
class ProgressionsController < ApplicationController

  def create
    @candidate = Candidate.find(params[:candidate_id])
    @progression = @candidate.progressions.create(progression_params)
    redirect_to candidate_path(@candidate)
  end

  def destroy
    @candidate = Candidate.find(params[:candidate_id])
    @progression = @candidate.progressions.find(params[:id])
    @progression.destroy
    redirect_to candidate_path(@candidate)
  end

  def progression_params
     params.require(:progression).permit(:status, :stage, :position, :pre_salary, :expect_salary, :source, :source_detail, :general_test,
                                          :general_test_checker, :tech_test ,:tech_test_checker)
  end
end











  # def index
  #   @progressions = Progression.all
  # end
  #
  # def new
  #   @candidate = Candidate.find(params[:candidate_id])
  #   @progression = Progression.new
  # end
  #
  # def show
  #   @progression = Progression.find(params[:id])
  # end
  #
  # def create
  #   # @candidate = Candidate.find(params[:candidate_id])
  #   @progression = Progression.new(progression_params)
  #
  #   if @progression.save
  #     redirect_to candidate_path(@candidate)
  #   else
  #     render 'new'
  #   end
  # end
  #
  # def update
  #   @candidate = Candidate.find(params[:id])
  #   @progression = Progression.find(params[:id])
  #
  #   if @progression.update(candidate_params)
  #     redirect_to candidates_url
  #   else
  #     # render 'show'
  #   end
  # end
  #
  # def destroy
  #   @progression = Progression.find(params[:id])
  #   @progression.destroy
  #   redirect_to candidates_url
  # end
  #
  # private
  # # def progression_params
  # #   params.require(:progression).permit(:status, :stage, :position, :pre_salary, :expect_salary, :source, :source_detail, :general_test,
  # #                                        :general_test_checker, :tech_test ,:tech_test_checker)
  # def progression_params
  #     params.require(:progression).permit(:status)
  # end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController

  def index
    @staffs = Staff.all
  end

  def new
    @staff = Staff.new
  end

  def show
    @staff = Staff.find(params[:id])
  end

  def create
    @staff = Staff.new(staff_params)

    if @staff.save
      redirect_to staffs_url
    else
      render 'new'
    end
  end

  def update
    @staff = Staff.find(params[:id])

    if @staff.update(staff_params)
      redirect_to staffs_url
    else
      render 'show'
    end
  end

  def destroy
    @staff = Staff.find(params[:id])
    @staff.destroy
    redirect_to staffs_url
  end

  private
  def staff_params
    params.require(:staff).permit(:name, :email, :phone, :gender )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/progressions_helper.rb
module ProgressionsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/candidates/detaa.html.erb
DEETAA

app/views/candidates/index.html.erb
<h1>Candidates List</h1>

<%= link_to 'New Candidate', new_candidate_path , class: "btn btn-default" %>

<table class="table" style="margin-top: 30px">
  <thead>
  <tr>
    <th>Name</th>
    <th>E-mail</th>
    <th>Phone No.</th>
  </tr>
  </thead>

  <tbody>
  <% @candidates.each do |candidate| %>
      <tr>
        <td><%= link_to candidate.name, candidate_path(candidate) %></td>
        <td><%= candidate.email %></td>
        <td><%= candidate.phone %></td>
        <td><%= link_to 'Destroy', candidate_path(candidate),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/candidates/new.html.erb
<%= form_for :candidate, url: candidates_path do |f| %>

    <% if @candidate.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@candidate.errors.count, "error") %> prohibited
            this candidate from being saved:
          </h2>
          <ul>
            <% @candidate.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="actions">
      <p class="form-inline">
        <%= f.label :name %>
        <a id="add_form_50"><%= f.text_field :name, {class: 'form-control' , :style => "max-width: 340px;"} %></a>
      </p>
      <p class="form-inline">
        <%= f.label :email %>
        <a id="add_form_50"><%= f.email_field :email, {class: 'form-control' , :style => "max-width: 340px;"} %></a>
      </p>
      <p class="form-inline">
        <%= f.label :gender %>
        <%= f.radio_button :gender, 'male', :checked => true , :style => "margin-left: 35px;" %>
        <%= label :gender_male, 'Male' %>
        <%= f.radio_button :gender, 'female', :style => "margin-left: 20px;" %>
        <%= label :gender_female, 'Female' %>
      </p>
      <p class="form-inline">
        <%= f.label :phone %>
        <a style="margin-left: 45px;"><%= f.text_field :phone, {class: 'form-control' , :style => "max-width: 340px;"} %></a>
      </p>
      <p class="form-inline">
        <%= f.label :address %>
        <a id="add_form_30"><%= f.text_area :address, {class: 'form-control' , :style => "max-width: 340px;"} %></a>
      </p>

      <%= f.check_box :blacklist , class: 'hidden' %>

      <div style="margin-top: 10px;">
        <%= f.submit "Add new candidate", class: "btn btn-success" %>
        <%= link_to 'Back', candidates_path , class: "btn btn-primary" %>
      </div>

    </div>
<% end %>

app/views/candidates/paget.html.erb
paget

app/views/candidates/show.html.erb
<%= form_for :candidate, url: candidate_path(@candidate), method: :patch do |f| %>

<!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

      <title>Candidate</title>

      <!-- Bootstrap core CSS -->
      <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

      <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
      <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

      <!-- Custom styles for this template -->
      <!-- <link href="test.css" rel="stylesheet"> -->

      <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
      <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
      <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
    </head>

    <body>

    <div class="container">
      <div class="row" align="center">
        <div class="col-sm-2"  align="center" style="width: 185px; padding: 5px;">
          <div><img src="/images/rss.jpg" alt="rss feed" height="150px" width="150px" ></div>
          <div>ID : <%= @candidate.id %></div>
        </div>
        <div class="col-sm-2"  align="center" style="width: 185px; padding: 24px;">
          <p><%= f.submit "Submit", { class: "btn btn-success" , :style => "min-width: 100px;"} %></p>
          <p><%= link_to 'Back', candidates_path , {class: "btn btn-primary" , :style => "min-width: 100px;"} %></p>
          <p><%= link_to 'Delete', @candidate, method: :delete,
                         data: { confirm: 'Are you sure?' } ,
                         class:"btn btn-danger", :style => "min-width: 100px;" %></p>
        </div>
        <div class="col-sm-4"  style="width: 325px; padding: 19px;">
          <!--btnnnnnnnnnnnnnnnnnn-->
        </div>

        <!-- </div> -->
        <!-- Example row of columns -->
        <div class="row" >
          <div class="col-md-6" align="left"  style="width: 550px; padding: 19px;">
            <p class="form-inline">
              <%= f.label :name %>
              <a id="add_form_50"><%= f.text_field :name, {class: 'form-control' , :style => "min-width: 340px;"} %></a>
            </p>
            <p class="form-inline">
              <%= f.label :email %>
              <a id="add_form_50"><%= f.email_field :email, {class: 'form-control' , :style => "min-width: 340px;"} %></a>
            </p>
            <p class="form-inline">
              <%= f.label :gender %>
              <%= f.radio_button :gender, 'male', :checked => true , :style => "margin-left: 35px;" %>
              <%= label :gender_male, 'Male' %>
              <%= f.radio_button :gender, 'female', :style => "margin-left: 20px;" %>
              <%= label :gender_female, 'Female' %>
            </p>
            <p class="form-inline">
              <%= f.label :phone %>
              <a style="margin-left: 45px;"><%= f.text_field :phone, {class: 'form-control' , :style => "min-width: 340px;"} %></a>
            </p>
            <p class="form-inline">
              <%= f.label :address %>
              <a id="add_form_30"><%= f.text_area :address, {class: 'form-control' , :style => "min-width: 340px;"} %></a>
            </p>
            <p class="form-inline">
              <%= f.label :blacklist %>
              <a id="add_form_30"><%= f.check_box :blacklist %></a>
            </p>
          </div>
<% end %>

<!--COMENT-->

<h2>Interview</h2>
<%= render @candidate.comments %>
<%= render 'comments/form' %>

<h2>Progression</h2>
<%= render @candidate.progressions %>
<%= render 'progressions/form' %>

</div><!--END COMMENT-->
</div>
</div><!-- /.container -->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="../../dist/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

app/views/comments/_comment.html.erb
<p>
  <strong><%= comment.commenter %> :</strong>   <%= comment.body %> <%= link_to 'X', [comment.candidate, comment],
                                                                                method: :delete,
                                                                                data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@candidate, @candidate.comments.build]) do |f| %>
    <p>
      <%= f.label :commenter %><br>
      <%= f.text_field :commenter %>
    </p>
    <p>
      <%= f.label :detail %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "ARMS", root_path, id: "logo" %>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container" >
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!--           <a class="navbar-brand" href="#">Candidates</a> -->
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <!-- <li class="active"><a href="#">Home</a></li> -->
            <li><%= link_to "Candidate",    candidates_path %></li>
            <li><%= link_to "Staff",    staffs_path %></li>
            <li><%= link_to "Canlendar", '#' %></li>
            <li><%= link_to "Statistic", '#' %></li>
          </ul>
          <ul class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Username" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-default">Sign in</button>
          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vagrant</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/progressions/_form.html.erb
<%= form_for([@candidate, @candidate.progressions.build]) do |f| %>
    <p>
      <%= f.label :status %><br>
      <%= f.text_field :status %>
    </p>
    <p>
      <%= f.label :stage %><br>
      <%= f.text_field :stage %>
    </p>
    <p>
      <%= f.label :position %><br>
      <%= f.text_field :position %>
    </p>
    <p>
      <%= f.label :pre_salary %><br>
      <%= f.text_field :pre_salary %>
    </p>
    <p>
      <%= f.label :expect_salary %><br>
      <%= f.text_field :expect_salary %>
    </p>
    <p>
      <%= f.label :source %><br>
      <%= f.text_field :source %>
    </p>
    <p>
      <%= f.label :source_detail %><br>
      <%= f.text_field :source_detail %>
    </p>
    <p>
      <%= f.label :general_test %><br>
      <%= f.text_field :general_test %>
    </p>
    <p>
      <%= f.label :general_test_checker %><br>
      <%= f.text_field :general_test_checker %>
    </p>
    <p>
      <%= f.label :tech_test %><br>
      <%= f.text_field :tech_test %>
    <p>
      <%= f.label :tech_test_checker %><br>
      <%= f.text_field :tech_test_checker %>
    </p>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/progressions/_progression.html.erb
<p>
  <strong><%= progression.status %> :</strong>  <%= link_to 'X', [progression.candidate, progression],
                                                                                method: :delete,
                                                                                data: { confirm: 'Are you sure?' } %>
</p>

app/views/progressions/new.html.erb
<%= form_for :progression, url: progressions_path do |f| %>

      <p class="form-inline">
        <%= f.label :status %>
        <a id="add_form_30"><%= f.text_area :status, {class: 'form-control' , :style => "max-width: 340px;"} %></a>
      </p>

      <div style="margin-top: 10px;">
        <%= f.submit "Progression", class: "btn btn-success" %>
      </div>

    </div>
<% end %>

app/views/staffs/index.html.erb
<h1>Staffs List</h1>

<%= link_to 'New staff', new_staff_path , class: "btn btn-default" %>

<table class="table" style="margin-top: 30px">
  <thead>
  <tr>
    <th>Name</th>
    <th>E-mail</th>
    <th>Phone No.</th>
  </tr>
  </thead>

  <tbody>
  <% @staffs.each do |staff| %>
      <tr>
        <td><%= link_to staff.name, staff_path(staff) %></td>
        <td><%= staff.email %></td>
        <td><%= staff.phone %></td>
        <td><%= link_to 'Destroy', staff_path(staff),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/staffs/new.html.erb
<%= form_for :staff, url: staffs_path do |f| %>

    <% if @staff.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@staff.errors.count, "error") %> prohibited
            this staff from being saved:
          </h2>
          <ul>
            <% @staff.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="actions">
      <p class="form-inline">
        <%= f.label :name %>
        <a id="add_form_50"><%= f.text_field :name, {class: 'form-control' , :style => "min-width: 340px;"} %></a>
      </p>
      <p class="form-inline">
        <%= f.label :email %>
        <a id="add_form_50"><%= f.email_field :email, {class: 'form-control' , :style => "min-width: 340px;"} %></a>
      </p>
      <p class="form-inline">
        <%= f.label :gender %>
        <%= f.radio_button :gender, 'male', :checked => true , :style => "margin-left: 35px;" %>
        <%= label :gender_male, 'Male' %>
        <%= f.radio_button :gender, 'female', :style => "margin-left: 20px;" %>
        <%= label :gender_female, 'Female' %>
      </p>
      <p class="form-inline">
        <%= f.label :phone %>
        <a style="margin-left: 45px;"><%= f.text_field :phone, {class: 'form-control' , :style => "min-width: 340px;"} %></a>
      </p>
      <div style="margin-top: 10px;">
        <%= f.submit "Add new staff", class: "btn btn-success" %>
        <%= link_to 'Back', staffs_path , class: "btn btn-primary" %>
      </div>

    </div>
<% end %>